import React, {useEffect, useState } from 'react';
import Button from '@mui/material/Button';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';

const Ordination = ({ handleNavigateTo }) => {
    const [parameters, setParameters] = useState({
        glomby: '',
        algorithm: '',
        PCA_Components: '',
        distmehod: '',
        subsetby: '',
        compareby: '',
        colourby: '',
        colorby: '',
        shapeby: '',
        samplesToKeep: '',
        featuresToKeep: '',
        samplesToHighlight: '',
        ignoreunclassified: true,
        applyfilters: 'none',
        featcutoff: '',
        GenomeCompletenessCutoff: '',
        discard_SDoverMean_below: '',
        asPPM: true,
        normalization: 'relabund',
        PPM_normalize_to_bases_sequenced: false,
        assay_for_matrix: 'BaseCounts',
        use_letters_as_shapes: false,
        sizeby: '',
        connectby: '',
        connection_orderby: '',
        textby: '',
        ellipseby: '',
        dotsize: 2,
        log2tran: false,
        tsne_perplx: '',
        max_neighbors: 15,
        permanova: false,
        plotcentroids: false,
        highlight_centroids: false,
        show_centroid_distances: false,
        calculate_centroid_distances_in_all_dimensions: false,
        addtit: '',
        cdict: '',
        grid: false,
        forceaspectratio: '',
        numthreads: 1,
        return_coordinates_matrix: false,
        permanova_permutations: 10000,
        include_components_variance_plot: false,
        class_to_ignore: 'N_A',
    });
}
