#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(RCurl))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(futile.logger))
suppressPackageStartupMessages(library(parallel))
suppressPackageStartupMessages(library(benchmarkme))
suppressPackageStartupMessages(library(openxlsx))
#####################################
# Define System-specific Functions ##
#####################################
if ((.Platform$OS.type) != "unix"){
    stop("This script only works on UNIX. Install Linux and try again.")
}

#Get slurm job ID
slurmjobid <- as.character(Sys.getenv("SLURM_JOB_ID"))

#Decide which kind of system you are on.
if(nchar(slurmjobid) < 3){
   print("You are not on a Slurm Workload Cluster")
   detectBatchCPUs <- function() {
        ncores <- detectCores()
        if (is.na(ncores)) {
            stop("Could not determine how many CPUs you have. Aborting.")
        }
        return(ncores)
    }

    detectAvailRAM <- function(){
        totmembytes<-as.numeric(get_ram())

        return(totmembytes)
    }

} else {
    print(paste("You are on a Slurm Workload Manager Cluster under jobID", slurmjobid))
    detectBatchCPUs <- function() {
        slurmjobid <- as.character(Sys.getenv("SLURM_JOB_ID"))
        ncores <- as.numeric(Sys.getenv("SLURM_CPUS_PER_TASK"))

        if (is.na(ncores)) {
            sacctraw <- system2("sacct", args = c("-j", slurmjobid, "-X", "-P"), stdout = TRUE)
            jobinforaw <- sacctraw[2]
            jobinfoheaders <- sacctraw[1]
            jobinfo <- unlist(strsplit(jobinforaw, split="\\|"))
            names(jobinfo) <- unlist(strsplit(jobinfoheaders, split="\\|"))
            ncores <- as.integer(jobinfo["AllocCPUS"])
            print(jobinfo)
            if (is.na(ncores)) {
                stop("Could not determine how many CPUs you have. Aborting.")
            }
        }

        return(ncores)
    }

    detectAvailRAM <- function(){
        mempercpu <- as.integer(Sys.getenv("SLURM_MEM_PER_CPU"))
        mempernode <- as.integer(Sys.getenv("SLURM_MEM_PER_NODE"))
        cpuspertask <- as.integer(Sys.getenv("SLURM_CPUS_PER_TASK"))

        if (!(is.na(mempernode))){
            totmem <- mempernode
        } else {
            totmem <- mempercpu * cpuspertask
        }

        totmembytes <- totmem * 1000000

        return(totmembytes)
    }
}

############################
## Define other functions ##
############################
filetype <- function(path){
    f = file(path)
    ext = summary(f)$class
    close.connection(f)
    ext
}

# get path of running script
getScriptPath <- function() {
    cmdArgs <- commandArgs(trailingOnly = FALSE)
    needle <- "--file="
    match <- grep(needle, cmdArgs)
    if (length(match) > 0) {
        return(dirname(normalizePath(sub(needle, "", cmdArgs[match]))))
    } else {
        return(dirname(normalizePath(sys.frames()[[1]]$ofile)))
    }
}

#Fix path relativity
fixrelpath <- function(JAMSpath = NULL){
    require(R.utils)
    if (!(isAbsolutePath(JAMSpath))){
        fixedpath <- getAbsolutePath(JAMSpath)
    } else {
        fixedpath <- JAMSpath
    }
    #Chomp a "/" from the end of paths
    fixedpath <- gsub("/$", "", fixedpath)

    return(fixedpath)
}

analyze_fastq_filename <- function(fn = NULL, maintain_Illumina_format = FALSE){

    filefacts <- list()
    fnsplit <- unlist(strsplit(fn, split = "\\."))
    if (tail(fnsplit, n = 1) == "gz"){
        filefacts$gunzipped <- TRUE
        fnbody <- paste0(rev(rev(fnsplit)[3:length(fnsplit)]), collapse = ".")
        filefacts$suffix <- paste0(tail(fnsplit, n = 2), collapse = ".")
    } else {
        filefacts$gunzipped <- FALSE
        fnbody <- paste0(rev(rev(fnsplit)[2:length(fnsplit)]), collapse = ".")
        filefacts$suffix <- tail(fnsplit, n = 1)
    }

    contains_lane_info <- any(c("L001", "L002", "L003", "L004", "L005", "L006", "L007", "L008") %in% tail(unlist(strsplit(fnbody, split = "_")), n = 4))
    contains_paired_read_info <- any(c("R1", "R2") %in% tail(unlist(strsplit(fnbody, split = "_")), n = 4))
    is_Illumina_output <- (tail(unlist(strsplit(fnbody, split = "_")), n = 1) == "001")
    numfnbodysegments <- length(unlist(strsplit(fnbody, split = "_")))

    if (!is_Illumina_output){
        if (contains_paired_read_info){
            filefacts$OriPrefix <- paste0(unlist(strsplit(fnbody, split = "_"))[1:(numfnbodysegments - 1)], collapse = "_")
            filefacts$Read <- tail(unlist(strsplit(fnbody, split = "_")), n = 1)
        } else {
            filefacts$OriPrefix <- fnbody
            filefacts$Read <- ""
        }
        filefacts$Appendage <- paste0(".", filefacts$suffix)
    } else {
        filefacts$Read <- tail(unlist(strsplit(fnbody, split = "_")), n = 2)[1]

        if (contains_lane_info){
            filefacts$OriPrefix <- paste0(unlist(strsplit(fnbody, split = "_"))[1:(numfnbodysegments - 4)], collapse = "_")
            filefacts$Lane <- tail(unlist(strsplit(fnbody, split = "_")), n = 3)[1]
            filefacts$SampNum <- tail(unlist(strsplit(fnbody, split = "_")), n = 4)[1]
            if (maintain_Illumina_format){
                filefacts$Appendage <- paste(paste(filefacts$SampNum, filefacts$Lane, filefacts$Read, "001", sep = "_"), filefacts$Container, sep = ".")
            } else {
                filefacts$Appendage <- paste(filefacts$Read, filefacts$suffix, sep = ".")
            }
        } else {
            filefacts$OriPrefix <- paste0(unlist(strsplit(fnbody, split = "_"))[1:(numfnbodysegments - 3)], collapse = "_")
            filefacts$Lane <- ""
            filefacts$SampNum <- tail(unlist(strsplit(fnbody, split = "_")), n = 3)[1]
            if (maintain_Illumina_format){
                filefacts$Appendage <- paste(paste(filefacts$SampNum, filefacts$Read, "001", sep = "_"), filefacts$suffix, sep = ".")
            } else {
                filefacts$Appendage <- paste(filefacts$Read, filefacts$suffix, sep = ".")
            }
        }
    }

    return(filefacts)
}

#Extract Flowcell from a path following Illumina folder convention. Returns NA if absent.
extract_flowcell <- function(filepath){
    components <- unlist(strsplit(filepath, split = "/"))
    fc_component <- components[grep("^Flowcell_", components)]
    if (length(fc_component) < 1){
        return(NA_character_)
    }
    fc_component <- tail(fc_component, n = 1)
    flowcell <- sub("^Flowcell_", "", fc_component)

    return(flowcell)
}

is.redundant <- function(vec){
    propunique <- length(unique(vec))/length(vec)
    if (propunique < 1){
        redundant = TRUE
    } else {
        redundant = FALSE
    }

    return(redundant)
}

find_container <- function(x) {
    prefsuff <- unlist(strsplit(rawfastqsdf$Filenames[x], split = "\\."))
    container <- paste(prefsuff[(which(prefsuff %in% c("fastq", "tar"))):(length(prefsuff))], collapse = ".")

    return(container)
}

check_prefixes <- function(opt = NULL){
    if (!is.null(opt$checkprefixexists)){
        if (length(opt$usedprefixes) > 0){
            #Compute the mask ONCE against the prefixes currently being processed,
            #and apply it consistently to both prefixestouse and any parallel
            #accessions vector, so the two never desynchronize.
            already_mask <- (opt$prefixestouse %in% opt$usedprefixes)
            opt$alreadyusedprexixes <- opt$prefixestouse[already_mask]
            if (length(opt$alreadyusedprexixes) > 0){
                cat("WARNING: THE FOLLOWING PREFIXES HAVE BEEN FOUND IN\n")
                cat(paste(as.character(opt$checkprefixexists), "\n"))
                cat(paste(paste0(opt$alreadyusedprexixes, collapse = ", "), "\n"))
                cat("THESE PREFIXES HAVE BEEN ELIMINATED FROM THE SWARM FILE GENERATED.\n")
                if (!is.null(opt$wantedaccessions)){
                    #Cull accessions with the SAME mask, before prefixestouse is altered.
                    opt$wantedaccessions <- opt$wantedaccessions[!already_mask]
                }
                opt$prefixestouse <- opt$prefixestouse[!already_mask]
            }
        }
    }

    return(opt)
}

#########################
# Get options from args #
#########################
defopt <- list()
defopt$verstr <- paste0("JAMSmakeswarm v", "1.1")
defopt$outputfolder <- getwd()
defopt$readsfolder <- NULL
defopt$hostspecies <- "human"
defopt$analysis <- "metagenome"
defopt$useipro <- FALSE
defopt$jamsdb <- NULL
defopt$swarmfile <- fixrelpath(JAMSpath = "JAMS.swarm")

option_list <- list(
    make_option(c("-r", "--readsfolder"), default = defopt$readsfolder, action="store",
                help = str_c("path to root directory where reads are (default: ", defopt$readsfolder, ")")),

    make_option(c("-o", "--outputfolder"), default = defopt$outputfolder, action="store",
                help = str_c("path to where you want the JAMSalpha outputs (default: ", defopt$outputfolder, ")")),

    make_option(c("-H", "--hostspecies"), default = defopt$hostspecies, action="store",
                help = str_c("Name or taxid of host species (default: ", defopt$hostspecies, ")")),

    make_option(c("-A", "--analysis"), default = defopt$analysis, action="store",
                help = str_c("Project type. Choose between metagenome, metatranscriptome, isolate or isolaternaseq. (default: ", defopt$analysis, ")")),

    make_option(c("-d", "--jamsdb"), default = defopt$jamsdb, action="store",
                help = str_c("Path to JAMS database.")),

    make_option(c("-p", "--prefixlist"), default = NULL, action="store",
                help = str_c("Text file with a list of read prefixes to restrict swarm to.")),

    make_option(c("-t", "--substitutionmap"), default = NULL, action="store",
                help = str_c("Tab limited text file for sample name substitution in the format: oldname[TAB]newname")),

    make_option(c("-x", "--substitutionspreadsheet"), default = NULL, action="store",
                help = str_c("Tab limited xlsx spreadsheet for sample name substitution. Will look for a column named OriPrefix and substitute that value for the corresponding one on the Sample column.")),

    make_option(c("-g", "--sralist"),
                default = NULL, action="store", help = str_c("List of SRA accessions to get reads for assembly.")),

    make_option(c("-a", "--gcalist"),
                default = NULL, action="store", help = str_c("List of GCA accessions to get assembly contigs from GenBank (example: GCA_000969225.1).")),

    make_option(c("-z", "--appendtoprefix"),
                default = NULL, action="store", help = str_c("Append this string to prefix. Example: -z Bis would generate a prefix in the form of PrefixBis")),

    make_option(c("-b", "--prependtoprefix"),
                default = NULL, action="store", help = str_c("Prepend this string to prefix. Example: -b New123 would generate a prefix in the form of New123Prefix")),

    make_option(c("-n", "--useipro"), default = FALSE, action="store_true",
                help = str_c("Use -n option in swarm file, for automatically launching InterproScan if on NIH Biowulf, if available.)")),

    make_option(c("-s", "--swarmfile"), default = defopt$swarmfile, action="store",
                help = str_c("File name for swarm file to be created (default: ", defopt$swarmfile, ")")),

    make_option(c("-l", "--split_swarmfile"), default = NULL, action="store",
                help = str_c("Split swarm into multiple files with this number of lines each. Filenames will be appended with numbers (Example: Project.swarm001, Project.swarm002, etc...). Omit for no splitting.")),

    make_option(c("-c", "--checkprefixexists"), default = NULL,
                action="store", help = str_c("Optional path to folder with banked .jams files. If prefix already exists a warning is issued.")),

    make_option(c("-v", "--version"), action="store_true",
                help ="report version")
)

args <- commandArgs(trailingOnly = TRUE)
opt <- parse_args(OptionParser(option_list = option_list), args)
opt <- merge.list(opt, defopt)

#####################
## Set environment ##
#####################

if (!is.null(opt$version)) {
    print(opt$verstr)
    quit()
}

opt$bindir <- getScriptPath()

for (pathtofix in c("readsfolder", "outputfolder", "prefixlist", "swarmfile", "jamsdb", "substitutionmap", "substitutionspreadsheet")){
    if (!is.null(opt[[pathtofix]])){
        opt[[pathtofix]] <- fixrelpath(opt[[pathtofix]])
    }
}

###################
## Main Function ##
###################

#Evaluate prefix restrictions. Order of precedence is spreadsheet, substitutionmap, prefixlist.
if (!(is.null(opt$substitutionspreadsheet))){

    substitutiondf <- read.xlsx(opt$substitutionspreadsheet)
    if (!all(c("Sample", "OriPrefix") %in% colnames(substitutiondf))){
        missingcols <- c("Sample", "OriPrefix")[!(c("Sample", "OriPrefix") %in% colnames(substitutiondf))]
        flog.info(paste("Unable to find the", paste0(missingcols, collapse = ", "), "column(s) in the spreadsheet."))
        if ("Sample" %in% colnames(substitutiondf)){
            flog.info("Found a Sample column in the spreadsheet. Prefixes will be restricted to those in this column.")
            wantedprefixes <- as.character(substitutiondf$Sample)
        }
    } else {
        substitutiondf <- substitutiondf[ , c("Sample", "OriPrefix")]
        substitutiondf$Sample <- as.character(substitutiondf$Sample)
        substitutiondf$OriPrefix <- as.character(substitutiondf$OriPrefix)
        wantedprefixes <- substitutiondf$OriPrefix
    }

} else if (!(is.null(opt$substitutionmap))){

    substitutiondf <- data.table::fread(opt$substitutionmap, stringsAsFactors = FALSE, data.table = FALSE, header = FALSE)
    substitutiondf <- substitutiondf[ , 1:2]
    colnames(substitutiondf) <- c("Sample", "OriPrefix")
    wantedprefixes <- as.character(substitutiondf$OriPrefix)

} else if (!(is.null(opt$prefixlist))){

    wantedprefixes <- data.table::fread(opt$prefixlist, stringsAsFactors = FALSE, data.table = FALSE, header = FALSE)
    wantedprefixes <- as.character(wantedprefixes[, 1])
    substitutiondf <- NULL

} else {

    substitutiondf <- NULL
    wantedprefixes <- NULL

}

commonoptions <- paste("-d", opt$jamsdb, "-A", opt$analysis, "-o", opt$outputfolder, "-H", opt$hostspecies, collapse = " ")
if (opt$useipro == TRUE) {
    commonoptions <- paste(commonoptions, "-n", collapse = " ")
}

finalswarm <- NULL
swarm <- NULL

if (!is.null(opt$checkprefixexists)){
    cat("Checking if prefixes in swarm file coincide with prefixes in:\n")
    cat(paste(as.character(opt$checkprefixexists), "\n"))
    jamsfns <- list.files(path = opt$checkprefixexists, pattern = ".jams$", full.names = FALSE, recursive = TRUE, include.dirs = FALSE)
    #Guard against an empty banked folder, which would make 1:length(jamsfns) misbehave.
    if (length(jamsfns) > 0){
        opt$usedprefixes <- sapply(jamsfns, function(x) { tail(unlist(strsplit(unlist(strsplit(x, split = "\\."))[1], split = "\\/")), n = 1) }, USE.NAMES = FALSE)
    } else {
        flog.info("No banked .jams files found in the checkprefixexists folder; no prefixes will be excluded on that basis.")
        opt$usedprefixes <- character(0)
    }
}

if (!(is.null(opt$readsfolder))){
    flog.info("Searching for reads files in reads folder.")
    #Anchor to end of basename so companion files (.md5, etc.) are not picked up.
    rawfastqpaths <- list.files(path = opt$readsfolder, pattern = "fastq$|gz$", full.names = TRUE, recursive = TRUE)
    rawfastqpaths <- rawfastqpaths[grepl("(fastq|fastq\\.gz)$", basename(rawfastqpaths))]

    if (length(rawfastqpaths) < 1){
        flog.info("No fastq or fastq.gz files found in the reads folder supplied. Aborting.")
        q()
    }

    rawfastqnames <- sapply(rawfastqpaths, function(x) { tail(unlist(strsplit(x, split = "/")), n = 1) }, USE.NAMES = FALSE)
    datasetids <- sapply(rawfastqpaths, function(x) { tail(unlist(strsplit(x, split = "/")), n = 2)[1] }, USE.NAMES = FALSE)
    flowcells <- sapply(rawfastqpaths, extract_flowcell, USE.NAMES = FALSE)

    rawfastqsdf <- data.frame(Filenames = rawfastqnames, Filepaths = rawfastqpaths, DatasetIDs = datasetids, Flowcell = flowcells, stringsAsFactors = FALSE)

    rawfastqsdf$Read <- sapply(rawfastqsdf$Filenames, function(x) { analyze_fastq_filename(fn = x)[["Read"]] }, USE.NAMES = FALSE)
    rawfastqsdf$Container <- sapply(1:nrow(rawfastqsdf), function(x) { find_container(x) })
    rawfastqsdf$OriPrefix <- sapply(rawfastqsdf$Filenames, function(x) { analyze_fastq_filename(fn = x)[["OriPrefix"]] }, USE.NAMES = FALSE)

    if (!(is.null(wantedprefixes))){
         rawfastqsdf <- subset(rawfastqsdf, OriPrefix %in% wantedprefixes)
         if (nrow(rawfastqsdf) < 1){
             flog.info("Could not find a single prefix requested in the reads folder supplied.")
             q()
         }
         #Report any requested prefixes that were NOT found, which is easy to miss otherwise.
         notfound <- wantedprefixes[!(wantedprefixes %in% rawfastqsdf$OriPrefix)]
         if (length(notfound) > 0){
             flog.warn(paste("The following requested prefixes were NOT found in the reads folder:", paste0(notfound, collapse = ", ")))
         }
    }

    #Vet OriPrefix uniqueness before assigning final prefixes, to protect the swarm.
    OriPrefix_flowcell_pairs <- unique(rawfastqsdf[ , c("OriPrefix", "Flowcell")])
    OriPrefix_spanning_flowcells <- names(which(table(OriPrefix_flowcell_pairs$OriPrefix) > 1))
    if (length(OriPrefix_spanning_flowcells) > 0){
        flog.warn(paste("The following OriPrefixes appear across more than one flowcell:", paste0(OriPrefix_spanning_flowcells, collapse = ", ")))
        flog.warn("Each will yield a single swarm line pooling files from all its flowcells. If that is not intended, disambiguate before proceeding.")
    }

    if (!is.null(substitutiondf)){
        rawfastqsdf <- left_join(rawfastqsdf, substitutiondf, by = "OriPrefix")
        colnames(rawfastqsdf)[which(colnames(rawfastqsdf) == "Sample")] <- "Prefix"
    } else {
        colnames(rawfastqsdf)[which(colnames(rawfastqsdf) == "OriPrefix")] <- "Prefix"
    }

    #Apply prepend/append now, so the collision check reflects the FINAL prefix that will be written.
    rawfastqsdf$FinalPrefix <- paste0(opt$prependtoprefix, rawfastqsdf$Prefix, opt$appendtoprefix)

    opt$prefixestouse <- unique(rawfastqsdf$FinalPrefix)
    #Rename usedprefixes check to operate on the final prefix, matching what a banked .jams would carry.
    opt <- check_prefixes(opt = opt)

    for (p in 1:length(opt$prefixestouse)){
        finalprefix <- opt$prefixestouse[p]
        relevantfiles <- subset(rawfastqsdf, FinalPrefix == finalprefix)

        if (all(c("R1", "R2") %in% relevantfiles$Read)) {
            r1files <- relevantfiles$Filepaths[which(relevantfiles$Read == "R1")]
            r2files <- relevantfiles$Filepaths[which(relevantfiles$Read == "R2")]
            #Guard against multi-file (un-merged, multi-lane) inputs, which would silently
            #vectorize into multiple -f/-r fragments and build a malformed command.
            if (length(r1files) > 1 || length(r2files) > 1){
                flog.warn(paste0("Prefix ", finalprefix, " resolves to more than one R1 or R2 file (", length(r1files), " R1, ", length(r2files), " R2). This usually means un-merged multi-lane reads. Join lanes first (JAMSjoinlanes) or supply a tarball. Skipping this prefix."))
                next
            }
            FR <- paste("-f", r1files, sep = " ")
            RR <- paste("-r", r2files, sep = " ")
            readsinput <- paste(FR, RR)
        } else {
            if (relevantfiles$Container[1] == "tar.gz"){
                readsinput <- paste("-t", relevantfiles$Filepaths[1])
            } else {
                readsinput <- paste("-U", relevantfiles$Filepaths[1])
            }
        }
        #FinalPrefix already includes prepend/append.
        swarm[p] <- paste("JAMSalpha", readsinput, commonoptions, "-p", finalprefix, collapse = " ")
    }
    #Drop any NULL entries left by skipped prefixes.
    swarm <- swarm[!is.na(swarm)]
    finalswarm <- append(swarm, finalswarm)
}

if (any(c((!is.null(opt$sralist)), (!is.null(opt$gcalist))))) {
    for(lst in c("sralist", "gcalist")){
        if(!is.null(opt[[lst]])){
            swarm <- NULL
            flag <- switch(lst, "sralist" = "-g", "gcalist" = "-a")
            wantedaccessions <- data.table::fread(opt[[lst]], stringsAsFactors = FALSE, data.table = FALSE, header = FALSE)
            opt$wantedaccessions <- as.character(wantedaccessions[, 1])
            cleanprefixes <- unname(sapply(opt$wantedaccessions, function(x) { gsub("_", "", x) }))
            baseprefixes <- unname(sapply(cleanprefixes, function (x) { unlist(strsplit(x, split = "\\."))[1] } ))
            #Apply prepend/append here too, for consistency with the reads branch.
            opt$prefixestouse <- paste0(opt$prependtoprefix, baseprefixes, opt$appendtoprefix)
            opt <- check_prefixes(opt = opt)

            #check_prefixes may have culled both vectors in lockstep; re-derive length safely.
            if (length(opt$prefixestouse) > 0){
                for (p in 1:length(opt$prefixestouse)){
                    finalprefix <- opt$prefixestouse[p]
                    accession <- opt$wantedaccessions[p]
                    readsinput <- paste(flag, accession)
                    swarm[p] <- paste("JAMSalpha", readsinput, commonoptions, "-p", finalprefix, collapse = " ")
                }
                finalswarm <- append(swarm, finalswarm)
            }
            #Reset accessions so a subsequent list iteration does not inherit a stale vector.
            opt$wantedaccessions <- NULL
        }
    }
}

#Write swarm file to system
if (length(finalswarm) < 1){
    flog.warn("No swarm lines were generated. Nothing to write.")
    q()
}

if (!is.null(opt$split_swarmfile)){
    swarmlist <- split(finalswarm, ceiling(seq_along(finalswarm) / as.numeric(opt$split_swarmfile)))
    for (swm in 1:length(swarmlist)){
        appendix <- str_pad(swm, nchar(length(swarmlist)), pad = "0")
        cat(swarmlist[[swm]], file = paste0(opt$swarmfile, appendix), sep = "\n")
    }
} else {
    cat(finalswarm, file = opt$swarmfile, sep = "\n")
}

flog.info(paste("Wrote", length(finalswarm), "swarm line(s)."))